%YAML 1.2
# SPDX-FileCopyrightText: © 2018–2019, Daniel De Matteis <libretro@gmail.com>
# SPDX-FileCopyrightText: © 2018, Alfredo Monclus <alfredomonclus@gmail.com>
# SPDX-FileCopyrightText: © 2019, Mohmoud <devmohmoud@gmail.com>
# SPDX-FileCopyrightText: © 2024, Peter J. Mello <admin@petermello.net>
#
# SPDX-License-Identifier: MIT
---

language: python

python:
  - "3.8"

before_install:
  - python -m pip install --upgrade pip

install:
  - python -m pip install mkdocs
  - python -m pip install $(mkdocs get-deps | LC_ALL="C" tr '\n' ' ')

script:
  - mkdocs build
...
