# SPDX-FileCopyrightText: © 2024, Viačasłaŭ Chalikin <viachaslavic@outlook.com>
# SPDX-FileCopyrightText: © 2026, Ömercan Kömür <fpscan@gmail.com>
#
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
  ".git/",      # Version control files
  "archive/*",  # Archive files
]

# Match Inside a Word - Case Insensitive
[default.extend-words]
ue = "ue"          # Nestopia UE
sav = "sav"        # .sav file extension
kernal = "kernal"  # Commodore's low-level Operating System
