#!/bin/sh
# SPDX-FileCopyrightText: © 2018, Daniel De Matteis <libretro@gmail.com>
# SPDX-FileCopyrightText: © 2018, Andrés Suarez <fr500@users.noreply.github.com>
# SPDX-FileCopyrightText: © 2018, Brad Parker <cbparker@gmail.com>
#
# SPDX-License-Identifier: MIT

git fetch

git reset --hard origin/master

mkdocs build
